flex-wrap as a prop
bkzl/vue-fraction-grid pull request #11
Opened 2017-08-07 16:46 UTC by guibarscevicius

Add flex-wrap: nowrap as a prop (defaults to 'wrap')

2017-08-13 15:49 UTC, bartkozal requested changes
Hey, thank you so much for your contribution! 🙇 

I left two comments to make the code a bit cleaner. Can I also ask you to update tests and mention the new prop in the documentation? You will find necessary scripts to work on them in package.json.

2017-08-13 15:49 UTC, bkzl commented on components/Grid.vue
> +    nowrap: String,
You could specify the default value here:

```js
wrap: {
  type: String,
  default: 'wrap'
}
```

2017-08-13 15:49 UTC, bkzl commented on components/Grid.vue
> +        flexWrap: isUndefined(this.nowrap) ? 'wrap' : 'nowrap'
So with the default value initially set this one can be simplified to:

```js
flexWrap: this.wrap
```

2017-08-28 17:51 UTC, closed without merging

2017-08-28 17:53 UTC, guibarscevicius commented
Sorry, dont know what happened with the branches. Reopening the PR with changes.